version: '3'

services:
  frontend:
    build:
      context: ./FE
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./BE
    volumes:
      - ./BE:/app
    ports:
      - "1111:1111"
